// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

/*
Package go_ys_service_user is a generated protocol buffer package.

It is generated from these files:
	proto/user/user.proto

It has these top-level messages:
	UserInfo
	UserInfoRe
	UserRegister
	UserRegisterRe
	UserLogin
	UserLoginRe
*/
package go_ys_service_user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserInfo struct {
	UserName string `protobuf:"bytes,1,opt,name=user_name,json=userName" json:"user_name,omitempty"`
}

func (m *UserInfo) Reset()                    { *m = UserInfo{} }
func (m *UserInfo) String() string            { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()               {}
func (*UserInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UserInfo) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type UserInfoRe struct {
	UserId    int64  `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	UserName  string `protobuf:"bytes,2,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	FirstName string `protobuf:"bytes,3,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
}

func (m *UserInfoRe) Reset()                    { *m = UserInfoRe{} }
func (m *UserInfoRe) String() string            { return proto.CompactTextString(m) }
func (*UserInfoRe) ProtoMessage()               {}
func (*UserInfoRe) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UserInfoRe) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserInfoRe) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserInfoRe) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

type UserRegister struct {
	UserName  string `protobuf:"bytes,1,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	FirstName string `protobuf:"bytes,2,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	Pwd       string `protobuf:"bytes,3,opt,name=pwd" json:"pwd,omitempty"`
}

func (m *UserRegister) Reset()                    { *m = UserRegister{} }
func (m *UserRegister) String() string            { return proto.CompactTextString(m) }
func (*UserRegister) ProtoMessage()               {}
func (*UserRegister) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UserRegister) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserRegister) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UserRegister) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

type UserRegisterRe struct {
	Mess string `protobuf:"bytes,1,opt,name=mess" json:"mess,omitempty"`
}

func (m *UserRegisterRe) Reset()                    { *m = UserRegisterRe{} }
func (m *UserRegisterRe) String() string            { return proto.CompactTextString(m) }
func (*UserRegisterRe) ProtoMessage()               {}
func (*UserRegisterRe) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UserRegisterRe) GetMess() string {
	if m != nil {
		return m.Mess
	}
	return ""
}

type UserLogin struct {
	UserName string `protobuf:"bytes,1,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	Pwd      string `protobuf:"bytes,2,opt,name=pwd" json:"pwd,omitempty"`
}

func (m *UserLogin) Reset()                    { *m = UserLogin{} }
func (m *UserLogin) String() string            { return proto.CompactTextString(m) }
func (*UserLogin) ProtoMessage()               {}
func (*UserLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UserLogin) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserLogin) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

type UserLoginRe struct {
	UserTf bool `protobuf:"varint,1,opt,name=UserTf" json:"UserTf,omitempty"`
}

func (m *UserLoginRe) Reset()                    { *m = UserLoginRe{} }
func (m *UserLoginRe) String() string            { return proto.CompactTextString(m) }
func (*UserLoginRe) ProtoMessage()               {}
func (*UserLoginRe) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UserLoginRe) GetUserTf() bool {
	if m != nil {
		return m.UserTf
	}
	return false
}

func init() {
	proto.RegisterType((*UserInfo)(nil), "go.ys.service.user.UserInfo")
	proto.RegisterType((*UserInfoRe)(nil), "go.ys.service.user.UserInfoRe")
	proto.RegisterType((*UserRegister)(nil), "go.ys.service.user.UserRegister")
	proto.RegisterType((*UserRegisterRe)(nil), "go.ys.service.user.UserRegisterRe")
	proto.RegisterType((*UserLogin)(nil), "go.ys.service.user.UserLogin")
	proto.RegisterType((*UserLoginRe)(nil), "go.ys.service.user.UserLoginRe")
}

func init() { proto.RegisterFile("proto/user/user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0xb5, 0x4d, 0x8d, 0xc9, 0x54, 0x44, 0x16, 0xad, 0x12, 0xad, 0x96, 0x45, 0xd1, 0xd3, 0x16,
	0xf4, 0xe6, 0xd1, 0x8b, 0x04, 0xd4, 0xc3, 0xa2, 0x17, 0x11, 0x24, 0x9a, 0x49, 0xc8, 0x21, 0x49,
	0xd9, 0x8d, 0x8a, 0xff, 0xdb, 0x1f, 0x20, 0x33, 0x8d, 0xb1, 0x1f, 0x34, 0x5e, 0xc2, 0xcc, 0xbc,
	0x37, 0xef, 0xbd, 0xb0, 0x03, 0xbb, 0x13, 0x53, 0x56, 0xe5, 0xf8, 0xdd, 0xa2, 0xe1, 0x8f, 0xe2,
	0x5e, 0x88, 0xb4, 0x54, 0x5f, 0x56, 0x59, 0x34, 0x1f, 0xd9, 0x1b, 0x2a, 0x42, 0xe4, 0x19, 0x78,
	0x8f, 0x16, 0x4d, 0x58, 0x24, 0xa5, 0x38, 0x00, 0x9f, 0x66, 0x2f, 0x45, 0x94, 0xe3, 0x7e, 0x67,
	0xd4, 0x39, 0xf7, 0xb5, 0x47, 0x83, 0xfb, 0x28, 0x47, 0x19, 0x01, 0xfc, 0x12, 0x35, 0x8a, 0x3d,
	0xd8, 0x60, 0x6a, 0x16, 0x33, 0xd1, 0xd1, 0x2e, 0xb5, 0x61, 0x3c, 0xaf, 0xd1, 0x9d, 0xd7, 0x10,
	0x43, 0x80, 0x24, 0x33, 0xb6, 0x9a, 0xa2, 0x0e, 0xa3, 0x3e, 0x4f, 0xd8, 0xe2, 0x19, 0x36, 0xc9,
	0x42, 0x63, 0x9a, 0xd9, 0x0a, 0x4d, 0x6b, 0x9e, 0x05, 0xad, 0xee, 0x82, 0x96, 0xd8, 0x06, 0x67,
	0xf2, 0x19, 0xd7, 0x1e, 0x54, 0xca, 0x13, 0xd8, 0x9a, 0x55, 0xd7, 0x28, 0x04, 0xf4, 0x72, 0xb4,
	0xb6, 0x96, 0xe6, 0x5a, 0x5e, 0x81, 0x4f, 0xac, 0xdb, 0x32, 0xcd, 0x8a, 0xf6, 0x00, 0xb5, 0x43,
	0xf7, 0xcf, 0xe1, 0x14, 0xfa, 0xcd, 0xae, 0x46, 0x31, 0x00, 0x97, 0xda, 0x87, 0x84, 0x57, 0x3d,
	0x5d, 0x77, 0x17, 0xdf, 0x1d, 0xe8, 0x51, 0x29, 0x34, 0x78, 0xcd, 0xbf, 0x8e, 0xd4, 0xf2, 0xe3,
	0xa8, 0xd9, 0xbc, 0x81, 0xfc, 0x8f, 0xa1, 0x51, 0xae, 0x89, 0x10, 0xd6, 0xa7, 0xd9, 0x87, 0xab,
	0xe8, 0x0c, 0x07, 0xc7, 0xad, 0x30, 0x4b, 0xdd, 0x41, 0xff, 0x06, 0xab, 0xe6, 0x3a, 0x0e, 0x57,
	0x6d, 0x10, 0x1a, 0x1c, 0xb5, 0xa1, 0x24, 0x77, 0x3d, 0x78, 0xda, 0x51, 0xe3, 0x65, 0xd2, 0xab,
	0xcb, 0xc7, 0x79, 0xf9, 0x13, 0x00, 0x00, 0xff, 0xff, 0xc0, 0xb6, 0x70, 0x5b, 0xb5, 0x02, 0x00,
	0x00,
}
