// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/cap/ysnew.proto

package go_micro_service_ysnew

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for YsServer service

func NewYsServerEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for YsServer service

type YsServerService interface {
	SayHello(ctx context.Context, in *SayInfo, opts ...client.CallOption) (*ReInfo, error)
}

type ysServerService struct {
	c    client.Client
	name string
}

func NewYsServerService(name string, c client.Client) YsServerService {
	return &ysServerService{
		c:    c,
		name: name,
	}
}

func (c *ysServerService) SayHello(ctx context.Context, in *SayInfo, opts ...client.CallOption) (*ReInfo, error) {
	req := c.c.NewRequest(c.name, "YsServer.SayHello", in)
	out := new(ReInfo)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for YsServer service

type YsServerHandler interface {
	SayHello(context.Context, *SayInfo, *ReInfo) error
}

func RegisterYsServerHandler(s server.Server, hdlr YsServerHandler, opts ...server.HandlerOption) error {
	type ysServer interface {
		SayHello(ctx context.Context, in *SayInfo, out *ReInfo) error
	}
	type YsServer struct {
		ysServer
	}
	h := &ysServerHandler{hdlr}
	return s.Handle(s.NewHandler(&YsServer{h}, opts...))
}

type ysServerHandler struct {
	YsServerHandler
}

func (h *ysServerHandler) SayHello(ctx context.Context, in *SayInfo, out *ReInfo) error {
	return h.YsServerHandler.SayHello(ctx, in, out)
}
